enable_entity:
  name: Enable Entity
  description: Enable a disabled entity through Entity Manager
  fields:
    entity_id:
      name: Entity ID
      description: The entity ID to enable
      required: true
      example: "sensor.my_sensor"
      selector:
        entity: {}

disable_entity:
  name: Disable Entity
  description: Disable an enabled entity through Entity Manager
  fields:
    entity_id:
      name: Entity ID
      description: The entity ID to disable
      required: true
      example: "sensor.my_sensor"
      selector:
        entity: {}
